config/routes.rb
Myapp::Application.routes.draw do
  get "status/show"

  resources :groups
  resource :status, :only => [:show] 

  resources :rates, :only => [:index, :edit, :update, :show]
  resources :sessions, :except => ["destroy","update","edit"]

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :g_id, :g_name

  validates :g_id, :presence => true
  validates :g_name, :presence => true
 
  validates_uniqueness_of :g_id
  validates_uniqueness_of :g_name
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :brate_id, :comment, :g_id, :point, :rate_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :g_id, :u_id, :u_name,:password_digest, 
    :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  # GET /rates
  # GET /rates.json
  def index
    
    @login = cookies[:key]
    
    #@rates = Rate.all
    @rates = Rate.find_all_by_rate_id(session[:user_u_id])
    #@rates = Rate.find_all_by_groupid(params["g1"])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Group.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json:@reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @reports = Rate.find_by_sql(['select r.g_id, g.g_name,  r.rate_id, u1.u_name as rate_name,  r.brate_id, u2.u_name as brate_name, r.point, r.comment  from rates r inner join groups g on r.g_id = g.g_id inner join users u1 on r.rate_id = u1.u_id inner join users u2 on r.brate_id = u2.u_id  where r.g_id = ? order by brate_id', params[:id]])

    @lists = Rate.find_by_sql(['SELECT r.brate_id, u.u_name as brate_name FROM RATES r INNER JOIN USERS u ON u.u_id = r.brate_id where r.g_id = ? group by brate_id order by brate_id', params[:id]])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reports }
      format.json { render json: @lists }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    render 'login', :layout => true
  end
  
  def new
    @user = User.new
  end

  def create
    user = User.find_by_u_id params[:account]
    if user && user.authenticate(params[:pass])
      session[:user_id] = user.id
      session[:user_u_id] = user.u_id

      @login = User.find_by_u_id params[:account]

      cookies[:key] = @login

  	   respond_to do |format|
	       format.html {render 'login_success'}
	       format.json {render :json => @login}
        end
    else
      render 'login_failure', :layout => true
    end
  end

  def show
    render 'show'
  end
  
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def show
   @groups = Rate.find_by_sql("select rates.g_id,users.u_name,rates.point from rates join users on rates.g_id = users.g_id")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @groups }
    end
  end
end  

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :g_id %><br />
    <%= f.text_field :g_id %>
  </div>
  <div class="field">
    <%= f.label :g_name %><br />
    <%= f.text_field :g_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>グループ編集</h1>

<%= render 'form' %>

<%= link_to '詳細表示', @group %> |
<%= link_to '戻る', groups_path %>

app/views/groups/index.html.erb
<h1>グループ管理画面</h1>

<table>
  <tr>
    <th>G</th>
    <th>G name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.g_id %></td>
    <td><%= group.g_name %></td>
    <td><%= link_to '詳細表示', group %></td>
    <td><%= link_to '編集', edit_group_path(group) %></td>
    <td><%= link_to '削除', group, method: :delete, data: { confirm: '本当に削除してもよろしいですか?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '新規作成', new_group_path %>

app/views/groups/new.html.erb
<h1>グループ新規作成</h1>

<%= render 'form' %>

<%= link_to '戻る', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>G:</b>
  <%= @group.g_id %>
</p>

<p>
  <b>G name:</b>
  <%= @group.g_name %>
</p>


<%= link_to '編集', edit_group_path(@group) %> |
<%= link_to '戻る', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp_test03</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :point %><br />
    <%= f.number_field :point %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<p>
  <b>Groupid:</b>
  <%= @rate.g_id %>
</p>

<p>
  <b>Rateid:</b>
  <%= @rate.rate_id %>
</p>

<p>
  <b>Brateid:</b>
  <%= @rate.brate_id %>
</p>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Listing rates</h1>

<table>
  <tr>
    <th>Groupid</th>
    <th>Rateid</th>
    <th>Brateid</th>
    <th>Point</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.g_id %></td>
    <td><%= rate.rate_id %></td>
    <td><%= rate.brate_id %></td>
    <td><%= rate.point %></td>
    <td><%= rate.comment %></td>
    <td><%= link_to 'Edit', edit_rate_path(rate) %></td>

  </tr>
<% end %>
</table>

<br />

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Groupid:</b>
  <%= @rate.g_id %>
</p>

<p>
  <b>Rateid:</b>
  <%= @rate.rate_id %>
</p>

<p>
  <b>Brateid:</b>
  <%= @rate.brate_id %>
</p>

<p>
  <b>Point:</b>
  <%= @rate.point %>
</p>

<p>
  <b>Comment:</b>
  <%= @rate.comment %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>

app/views/reports/index.html.erb
<h1>グループ一覧</h1>

<table>
  <tr>
    <th>グループ名</th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.g_name %></td>
    <td><%= link_to "Show", :controller => "reports", :action =>  "show", :id => report.g_id %></td>
  </tr>
<% end %>
</table>

app/views/reports/show.html.erb
<% content_for :header do %>
  <%= javascript_include_tag "reports/jquery-1.2.3.min.js" %>
  <%= javascript_include_tag "reports/jquery.jqchart.js" %>
<% end %>

<table>
  <tr>
    <th>グループ名</th>
    <th>評価者</th>
    <th>被評価者</th>
    <th>点数</th>
    <th>コメント</th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.g_name %></td>
    <td><%= report.rate_name %></td>
    <td><%= report.brate_name %></td>
    <td><%= report.point %></td>
    <td><%= report.comment %></td>
  </tr>
<% end %>
</table>

<% @lists.each do |list| %>
  <% @id = list.brate_id
     @rates  = []
     @points = []
  %>
  <% @reports.each do |report| %>
    <%if list.brate_id == report.brate_id %>
      <%
        @rates  << report.rate_name
        @points << report.point
      %>
    <% end %>
  <% end %>

<%= content_tag(:canvas, 'test', :id => sprintf('report_%s',@id), :height=>"200") %>
<script type="text/javascript">
  <%== sprintf("$(function(){$('#report_%s').jQchart(new chartSetting_%s())});",@id,@id) %>
  function chartSetting_<%=@id%>() {
    return { config : { type  : 'bar', 
                        title : '対象：<%=list.brate_name%>さん',
                        labelX : <%==@rates%>, 
                        colorSet : ['#A8FF50','#C8BCFF'],
                        scaleY : {min: 0,max:100,gap:20},
                      },
             data : [<%=@points%>]
            }
  }
</script>
<hr>
<% end %>

<%= @brate %>
<%= link_to '戻る', reports_path %>

app/views/status/show.html.erb
<% @page_title ="状況確認" %>
<h1><%= @page_title %></h1>

<table>
 <tr>
  <th width="150">所属グループ</th>
  <th width="150">氏名</th>
  <th width="105">入力ステータス</th>
 </tr>
<% @groups.each do |groups| %>
 <tr>
  <td><%= groups.g_id %></td>
  <td><%= groups.u_name %></td>
  <% if groups.point != nil %>
  <td>入力されています</td>
  <% else %>
  <td>入力されていません</td>
  <% end %>
 </tr>
<% end %>
</table>